/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#ffffff",
        background: "#fbf8ff",
        "bg-main": "#f5f7fa",
        "on-surface": "#1a1b22",
        "on-surface-variant": "#444653",
        "on-background": "#1a1b22",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f2fc",
        "surface-container": "#eeedf6",
        "surface-container-high": "#e9e7f1",
        "surface-container-highest": "#e3e1eb",
        "surface-dim": "#dad9e2",
        "surface-bright": "#fbf8ff",
        "surface-variant": "#e3e1eb",
        "surface-tint": "#3c55bf",
        "inverse-surface": "#2f3037",
        "inverse-on-surface": "#f1f0f9",
        outline: "#757684",
        "outline-variant": "#c5c5d5",
        primary: "#3953bd",
        "on-primary": "#ffffff",
        "primary-container": "#546cd7",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#dde1ff",
        "primary-fixed-dim": "#b9c3ff",
        "on-primary-fixed": "#001356",
        "on-primary-fixed-variant": "#1f3ba6",
        "inverse-primary": "#b9c3ff",
        secondary: "#754aa1",
        "on-secondary": "#ffffff",
        "secondary-container": "#ce9ffd",
        "on-secondary-container": "#5a3086",
        "secondary-fixed": "#f0dbff",
        "secondary-fixed-dim": "#dcb8ff",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#5c3187",
        tertiary: "#835100",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a56600",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffddb9",
        "tertiary-fixed-dim": "#ffb964",
        "on-tertiary-fixed": "#2b1700",
        "on-tertiary-fixed-variant": "#663e00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        "text-primary": "#1e293b",
        "text-secondary": "#64748b",
        "border-subtle": "#e2e8f0",
      },
      fontFamily: {
        rubik: ["Rubik", "Heebo", "sans-serif"],
        heebo: ["Heebo", "Rubik", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        body: ["Heebo", "Rubik", "sans-serif"],
        headline: ["Rubik", "Heebo", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["Inter", "ui-monospace", "monospace"],
        "body-lg": ["Rubik", "Heebo", "sans-serif"],
        "body-md": ["Rubik", "Heebo", "sans-serif"],
        "body-sm": ["Rubik", "Heebo", "sans-serif"],
        "headline-md": ["Rubik", "Heebo", "sans-serif"],
        "headline-sm": ["Rubik", "Heebo", "sans-serif"],
        "headline-lg-mobile": ["Rubik", "Heebo", "sans-serif"],
        "display-lg": ["Rubik", "Heebo", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-stock": ["Rubik", "Heebo", "sans-serif"],
        "sku-mono": ["Inter", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-stock": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "sku-mono": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        xs: "4px",
        base: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "20px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        card: "0px 1px 3px rgba(0,0,0,0.1)",
        "card-elevated": "0px 4px 12px rgba(0,0,0,0.05)",
        gradient: "0px 4px 12px rgba(102,126,234,0.4)",
        "gradient-lg": "0px 20px 40px -10px rgba(102,126,234,0.3)",
      },
      backgroundImage: {
        "brand-gradient": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      },
    },
  },
  plugins: [],
};
